### ISSUE TITLE
Improve UI of the app

### ISSUE THREAD

**Issue by krishnachaitanya0107** [krishnachaitanya0107/Youtube-Ad-Skipper#1]
Currently , the app has a very basic design . Try to implement an attractive UI .

**Comment by Sougata2** [comment]
Please assign me this issue.
Thanks

**Comment by Sougata2** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/91375163/195120141-f02e9bd3-254c-4b20-a2ee-3d1707dd0adf.png)

Final Result after changing the UI of the Ad Skipper window Fame.
